version: "3.9"
services:
  php-apache:
    build: .
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db


  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: logindb
      MYSQL_USER: loginuser
      MYSQL_PASSWORD: loginpass
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass

volumes:
  db_data:
